spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s
  datasource:
    url: jdbc:mysql://localhost:3308/dmmate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dmmate
    password: dmmate
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: localhost
    port: 1025
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    secret: "change-me-to-a-very-long-random-secret-key-please-rotate"
    access-token-validity-seconds: 900 # 15m
    refresh-token-validity-seconds: 1209600 # 14d