spring:
  config:
    import: "classpath:application-secret.yml"
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s
  datasource:
    url: jdbc:mysql://localhost:3308/dmmate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dmmate
    password: dmmate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.user}
    password: ${spring.mail.pass}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.debug: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    issuer: "dm-mate"
    secret: ${JWT_SECRET}
    access-exp-min: 1440
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace