spring:
  config:
    import: "classpath:application-secret.yml"
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s
  datasource:
    url: jdbc:mysql://localhost:3308/dmmate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dmmate
    password: dmmate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.user}
    password: ${spring.mail.pass}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.debug: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    secret: "change-me-to-a-very-long-random-secret-key-please-rotate"
    access-token-validity-seconds: 900 # 15m
    refresh-token-validity-seconds: 1209600 # 14d
logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
    org.springframework.boot.context.config: DEBUG